Fix some PIE and stack protecting compilation errors.
undefined reference to `_GLOBAL_OFFSET_TABLE_' caused by position independent executable
undefined reference to `__stack_chk_fail' caused by stack protector

or something